name: diffusion-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.8.0
      - diffusers==0.35.1
      - matplotlib==3.10.5